Q1: What is the total revenue generated by male vs female customer?

select gender, sum(purchase_amount)as revenue
from customer 
group by gender 

Q2: which customers used a discount but sill spent mor than the average purchase amount ?

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
      SELECT AVG(purchase_amount)
      FROM customer
  );


Q3: which are the top 5 products with the highest average review rating?

SELECT item_purchased, 
       Round(AVG(review_rating::numeric),2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

Q4: compare the average purchase amounts between standard and express shipping ?


SELECT shipping_type, 
       ROUND(AVG(purchase_amount), 2)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

Q5 do subscribed customers spend more? compare average spend and total 
revenue between subscribers and non-subscribers

select subscription_status,
count(customer_id)as total_customer,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;


Q6 segment customers into new, returning and loyal
based on their total number of purchases , and show the count of  each segment 

WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)
SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

Q7 what are the top 3 most purchased products within each category ?

with item_counts as (
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc)as item_rank
from customer
group by category, item_purchased

)
select item_rank,category, item_purchased,total_orders
from item_counts
where item_rank <= 3;

Q8 are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status

Q9 what is the revenue contribution of each age  group?

select age_group, sum(purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue desc;